export enum TodoActionTypes {
  ADD_TODO = '[TODO] ADD_TODO',
  DELETE_TODO = '[TODO] DELETE_TODO',
  UPDATE_TODO = '[TODO] UPDATE_TODO',
  UPDATE_TODOS_FILTER = '[TODO] UPDATE_TODOS_FILTER',
}
